### ISSUE TITLE
db.add() works only with array of objects despite the example

### ISSUE THREAD

**Issue by ogroppo** [ysnglt/csvdb#1]
It would be nice to have the ability to provide only the object as argument.

Currently:
for (const row of data) {
                          ^

TypeError: data[Symbol.iterator] is not a function
    at ParserStream.fastcsv.fromPath.on.on (/Users/orlando/dev/csv-graph/node_modules/csv-database/csv-editor/index.js:89:27)
    at emitOne (events.js:120:20)
    at ParserStream.emit (events.js:210:7)
    at spreadArgs (/Users/orlando/dev/csv-graph/node_modules/fast-csv/lib/extended.js:43:25)
    at ParserStream.emit (/Users/orlando/dev/csv-graph/node_modules/fast-csv/lib/parser/parser_stream.js:314:17)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ysnglt** [comment]
Thanks for the feedback. Looking into it.
